# Generated by Django 3.0.5 on 2020-09-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/search/images'),
        ),
    ]
